### ISSUE TITLE
大佬为啥不更新repo了

### ISSUE THREAD

**Issue by ghost** [ztygalaxy/Hello_HDU#9]
as above

**Comment by zty-hdu** [comment]
您好，    本邮箱暂停使用已久，    您的来信已为您自动转发至  ***@***.***,    为保持通信通畅，请您及时更新联系人信息。    祝好！        这一封自动回复邮件，请勿再次回复。

**Comment by ztygalaxy** [comment]
最近工作有点忙，会尽快抽空更新下～

**Comment by zty-hdu** [comment]
您好，    本邮箱暂停使用已久，    您的来信已为您自动转发至  ***@***.***,    为保持通信通畅，请您及时更新联系人信息。    祝好！        这一封自动回复邮件，请勿再次回复。
